version: '3.7'

services:
  app:
    container_name: app_container
    image: flask-app:1.0.0
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/database"
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    command: >
      bash -c "python setup.py &&
             python app.py"

  postgres:
    container_name: postgres_container
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
